version: "3.8"

services:
  db:
    container_name: kambal-db
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - /var/kambal/postgresql/data:/var/lib/postgresql/data
  api:
    container_name: kambal-api
    image: kambal:latest
    restart: always
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=kambal_db
      - DB_HOST=kambal-db
      - DB_PORT=5432
      - DB_DIALECT=postgres
      - DB_LOGGING=true
      - NODE_ENV=development
      - SECRET_KEY=kimisgwapa
      - DEFAULT_PASSWORD=kambal
      - LOG_LEVEL=0
      - SERVER_PORT=3000
    ports:
      - 3000:3000
    links:
      - db
    depends_on:
      - db
volumes:
  db:
    driver: local
  
