version: "3.8"

services:
  # db:
  #   container_name: hangad-mysql
  #   image: mysql:8.0
  #   restart: always
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=hangad_db
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - /tmp/hangad-data:/var/lib/mysql
  db:
    container_name: kambal-db
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - /tmp/postgresql/kambal-data:/var/lib/postgresql/data

  # pgadmin:
  #   container_name: hangad-pgadmin4
  #   image: dpage/pgadmin4:6.15
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - 5050:80

  # swagger:
  #  image: swaggerapi/swagger-ui
  #  container_name: swagger
  #  ports:
  #     - "9999:8080"
  #  environment:
  #     API_URL: http://localhost:3000/spec
  
  # swagger-editor:
  #   image: swaggerapi/swagger-editor
  #   container_name: "swagger-editor"
  #   restart: always
  #   ports:
  #     - 9998:8080

volumes:
  db:
    driver: local
